# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [2]:
cars1=pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv')

In [5]:
cars2=pd.read_csv('https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv')

### Step 4. Ops it seems our first dataset has some unnamed blank columns, fix cars1

In [ ]:
cars1.drop(cars1.columns[9:],axis=1,inplace = True)

### Step 5. What is the number of observations in each dataset?

In [21]:
cars1.shape

(198, 9)

In [24]:
cars2.shape

(200, 9)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [29]:
cars = pd.concat([cars1,cars2])

### Step 7. Ops there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [31]:
import numpy as np

In [38]:
cars.shape

(398, 9)

In [37]:
np.random.randint(15000,73000,size=cars.shape[0])

array([59638, 58198, 47169, 37165, 25056, 46322, 72947, 25435, 60768,
       72733, 45117, 24439, 22887, 31624, 47239, 60537, 33772, 50106,
       31835, 47668, 67126, 27750, 64844, 16061, 30268, 22302, 20775,
       51078, 68251, 21538, 19307, 27969, 45847, 41456, 31908, 57599,
       61822, 57335, 38840, 39451, 70804, 64418, 40255, 24173, 33447,
       29883, 38421, 20546, 66744, 30827, 15001, 58553, 66356, 57703,
       44810, 47464, 48270, 42055, 28225, 23887, 15525, 60106, 25003,
       57333, 46549, 35434, 67384, 53388, 39422, 25153, 49727, 52300,
       54501, 32910, 20321, 23239, 53886, 18897, 25561, 55666, 65499,
       30171, 66860, 27161, 39303, 71109, 52758, 43031, 22957, 39845,
       61633, 33750, 68950, 71645, 42245, 45126, 31937, 33468, 47762,
       26599, 42435, 18053, 26390, 50395, 59033, 47553, 35608, 42198,
       66613, 49690, 40442, 26320, 46564, 60725, 58794, 19729, 58556,
       69466, 26670, 18084, 37712, 71349, 56376, 68503, 27251, 65525,
       57199, 18435, 47759, 34554, 54731, 48091, 28180, 63812, 20157,
       26798, 42109, 38874, 63315, 20892, 19730, 49000, 54506, 51792,
       70558, 70852, 40976, 44149, 22544, 71030, 35553, 31721, 33844,
       57164, 45700, 66072, 69993, 69259, 45255, 70735, 15571, 45632,
       27226, 69963, 33144, 60510, 71171, 67306, 24051, 63397, 72723,
       47796, 47210, 61895, 43880, 63856, 34707, 64265, 21698, 70615,
       71962, 41083, 70962, 40943, 61748, 56855, 21773, 48137, 64345,
       32945, 56496, 63241, 63511, 17914, 31648, 48228, 46355, 21493,
       41819, 47487, 45933, 17354, 48766, 58710, 65465, 18719, 33384,
       51688, 20808, 21721, 63432, 17880, 63715, 40777, 48504, 30714,
       35593, 41105, 63449, 31233, 60775, 57847, 26020, 72787, 42639,
       30986, 23242, 66327, 28041, 58962, 18449, 44702, 69682, 31177,
       67252, 19490, 45082, 16496, 41637, 21701, 60051, 72115, 61595,
       51376, 28882, 51091, 40602, 50128, 64444, 48810, 18682, 41472,
       25141, 44749, 35342, 47909, 71307, 36121, 24720, 52022, 61038,
       44353, 58208, 18360, 71596, 39184, 53526, 36025, 72637, 54855,
       63235, 33021, 58497, 34308, 16927, 32785, 54560, 49250, 72139,
       50256, 26304, 31013, 69605, 40028, 63940, 65510, 44133, 47182,
       61617, 59539, 66789, 23727, 23867, 41209, 18336, 53094, 40184,
       30506, 64076, 37703, 27087, 43842, 36346, 65265, 60805, 41649,
       26335, 68795, 54803, 55211, 70407, 33956, 15501, 65884, 67564,
       69330, 38662, 53992, 70928, 19909, 64460, 60368, 31294, 57976,
       31992, 62808, 39625, 15950, 53477, 58269, 52433, 51729, 42523,
       43658, 42165, 45755, 54530, 15505, 51512, 22897, 70601, 39373,
       19793, 28023, 20395, 50501, 29047, 68261, 53783, 52481, 69494,
       66726, 56387, 46531, 38593, 23896, 19263, 36254, 55130, 29688,
       62114, 53623, 61470, 68368, 66447, 27028, 27621, 47224, 72708,
       37813, 40826, 30420, 53595, 64938, 69656, 26323, 30110, 71527,
       56468, 56532, 17603, 21648, 44548, 56476, 56964, 19748, 18233,
       35671, 62813, 68363, 47021, 37592, 16399, 26850, 72384, 42582,
       66863, 34028])

In [30]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw)
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster
16,18.0,6,199,97,2774,15.5,70,1,amc hornet
17,21.0,6,200,85,2587,16.0,70,1,ford maverick
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls
22,25.0,4,104,95,2375,17.5,70,2,saab 99e
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin
25,10.0,8,360,215,4615,14.0,70,1,ford f250
26,10.0,8,307,200,4376,15.0,70,1,chevy c20
27,11.0,8,318,210,4382,13.5,70,1,dodge d200
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510
...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe
183,36.0,4,107,75,2205,14.5,82,3,honda accord
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla
185,38.0,4,91,67,1965,15.0,82,3,honda civic
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto)
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx
188,25.0,6,181,110,2945,16.4,82,1,buick century limited
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel)
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion
191,22.0,6,232,112,2835,14.7,82,1,ford granada l
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 8. Add the column owners to cars

In [40]:
cars['owners'] = np.random.randint(15000,73000,size=cars.shape[0])

In [41]:
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,55722
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,26846
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,69767
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,59397
4,17.0,8,302,140,3449,10.5,70,1,ford torino,28250
5,15.0,8,429,198,4341,10.0,70,1,ford galaxie 500,50645
6,14.0,8,454,220,4354,9.0,70,1,chevrolet impala,49037
7,14.0,8,440,215,4312,8.5,70,1,plymouth fury iii,51629
8,14.0,8,455,225,4425,10.0,70,1,pontiac catalina,37256
9,15.0,8,390,190,3850,8.5,70,1,amc ambassador dpl,30191
10,15.0,8,383,170,3563,10.0,70,1,dodge challenger se,34812
11,14.0,8,340,160,3609,8.0,70,1,plymouth 'cuda 340,20047
12,15.0,8,400,150,3761,9.5,70,1,chevrolet monte carlo,38782
13,14.0,8,455,225,3086,10.0,70,1,buick estate wagon (sw),35751
14,24.0,4,113,95,2372,15.0,70,3,toyota corona mark ii,15911
15,22.0,6,198,95,2833,15.5,70,1,plymouth duster,62121
16,18.0,6,199,97,2774,15.5,70,1,amc hornet,61019
17,21.0,6,200,85,2587,16.0,70,1,ford maverick,55351
18,27.0,4,97,88,2130,14.5,70,3,datsun pl510,19637
19,26.0,4,97,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan,45929
20,25.0,4,110,87,2672,17.5,70,2,peugeot 504,57708
21,24.0,4,107,90,2430,14.5,70,2,audi 100 ls,39341
22,25.0,4,104,95,2375,17.5,70,2,saab 99e,51455
23,26.0,4,121,113,2234,12.5,70,2,bmw 2002,43842
24,21.0,6,199,90,2648,15.0,70,1,amc gremlin,16440
25,10.0,8,360,215,4615,14.0,70,1,ford f250,71759
26,10.0,8,307,200,4376,15.0,70,1,chevy c20,22294
27,11.0,8,318,210,4382,13.5,70,1,dodge d200,39941
28,9.0,8,304,193,4732,18.5,70,1,hi 1200d,71516
29,27.0,4,97,88,2130,14.5,71,3,datsun pl510,23080
...,...,...,...,...,...,...,...,...,...,...
170,27.0,4,112,88,2640,18.6,82,1,chevrolet cavalier wagon,68899
171,34.0,4,112,88,2395,18.0,82,1,chevrolet cavalier 2-door,71287
172,31.0,4,112,85,2575,16.2,82,1,pontiac j2000 se hatchback,61219
173,29.0,4,135,84,2525,16.0,82,1,dodge aries se,25514
174,27.0,4,151,90,2735,18.0,82,1,pontiac phoenix,52736
175,24.0,4,140,92,2865,16.4,82,1,ford fairmont futura,25559
176,23.0,4,151,?,3035,20.5,82,1,amc concord dl,38149
177,36.0,4,105,74,1980,15.3,82,2,volkswagen rabbit l,63442
178,37.0,4,91,68,2025,18.2,82,3,mazda glc custom l,27026
179,31.0,4,91,68,1970,17.6,82,3,mazda glc custom,26309
180,38.0,4,105,63,2125,14.7,82,1,plymouth horizon miser,69846
181,36.0,4,98,70,2125,17.3,82,1,mercury lynx l,61506
182,36.0,4,120,88,2160,14.5,82,3,nissan stanza xe,25872
183,36.0,4,107,75,2205,14.5,82,3,honda accord,54048
184,34.0,4,108,70,2245,16.9,82,3,toyota corolla,62304
185,38.0,4,91,67,1965,15.0,82,3,honda civic,72808
186,32.0,4,91,67,1965,15.7,82,3,honda civic (auto),22418
187,38.0,4,91,67,1995,16.2,82,3,datsun 310 gx,52432
188,25.0,6,181,110,2945,16.4,82,1,buick century limited,51559
189,38.0,6,262,85,3015,17.0,82,1,oldsmobile cutlass ciera (diesel),20790
190,26.0,4,156,92,2585,14.5,82,1,chrysler lebaron medallion,44497
191,22.0,6,232,112,2835,14.7,82,1,ford granada l,34640
192,32.0,4,144,96,2665,13.9,82,3,toyota celica gt,31220
193,36.0,4,135,84,2370,13.0,82,1,dodge charger 2.2,30826
194,27.0,4,151,90,2950,17.3,82,1,chevrolet camaro,19116
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,18921
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,21330
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,40066
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,21575
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,58798